name: notion_todo
description: Notion todo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

  # UI
  flash: ^3.0.5+1
  flutter_slidable: ^3.0.0
  grouped_list: ^5.1.2
  image_picker: ^1.0.1
  remixicon: ^1.0.0

  # Others
  equatable: ^2.0.5
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/app_icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.webp

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
